name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate dark stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=dark&bg_color=00000000&border_color=2F353E
          path: profile/stats-dark.svg
          token: ${{ secrets.PAT }}

      - name: Generate white stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=graywhite&bg_color=00000000&border_color=DFE4E9
          path: profile/stats-white.svg
          token: ${{ secrets.PAT }}

      # - name: Generate top languages card
      #   uses: readme-tools/github-readme-stats-action@v1
      #   with:
      #     card: top-langs
      #     options: username=${{ github.repository_owner }}&layout=compact&langs_count=6
      #     path: profile/top-langs.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate bse dark pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Konixy&repo=better-svelte-email&show_icons=true&theme=dark&bg_color=00000000&border_color=2F353E
          path: profile/pin-better-svelte-email-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate bse white pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Konixy&repo=better-svelte-email&show_icons=true&theme=graywhite&bg_color=00000000&border_color=DFE4E9
          path: profile/pin-better-svelte-email-white.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
